export enum InstructionCode {
  InitializeRetailer,
  FreezeRetailer,
  ThawRetailer,
  PlaceOrder,
  CancelOrder,
  RedeemOrder,
  ApproveOrder,
  RejectOrder,
  TransferRetailerOwnership,
}

export const ErrorMapping = [
  'Invalid instruction',
  'Invalid owner',
  'Invalid retailer owner',
  'Invalid order owner',
  'Invalid verifier',
  'Incorrect program id',
  'Operation overflowed',
  'Already constructed',
  'Cannot input a zero amount',
  'The order state is not active to action',
  'The order is not approved',
  'Cannot operate a pool with two same mints',
  'Invalid input data',
  'Invalid input data, the bid mint is not matching',
  'Invalid input data, the ask mint is not matching',
  'Invalid input data, the source bid account is not matching',
  'Invalid input data, the source ask account is not matching',
  'Invalid input data, the treasury ask account is not matching',
  'Invalid input data, the treasury bid account is not matching',
  'Locked time is not open',
  'The retailer is not active',
  'The retailer is not frozen',
  'The retailer is not matching with the order',
]
